### PR TITLE
Remove eroneous line directives in dynlink

### PR DESCRIPTION
**Pull request by shindere**
the dynlink other library contains several line directives which have
become incorrect, leading to an incorrect display of locations on
errors in the files in question. Similarly, the compiler is unable to
displaythe erroneous line because it can't find the source file
designated by these directives, which had been introduced in #648 (adding
plugin support to ocamlc) and
then modified in #1063.

### CODE REVIEW

**Comment by shindere** [comment]
Just updated the test reference files to take the new locations into
account but I think the present situation is not satisfactory since
the backtraces now look more confusing, whereas before the change
they were clear.

My understanding of the situation is that it is currently not possible
to have both coherent compilation error messages and error backtraces
because the dynlink files
are compiled with `othelribs/dynlink` as a current directory, whereas
the backtraces try to be relative to the toplevel of the source tree.

This makes me suspect that this PR  is actually hopeless since it won't
be possible to have both compile-time locations (in compilation errors)
and backtrace locations correct as lon as we do not compile from
the toplevel of the source tree.

Does that look correct?

**Comment by shindere** [comment]
As a complementary note, I do think that the locations reported on trunk in
backtraces involving Dynblink are wrong at least in terms of line numbers
and that the currnet PR does fix that.



Although the reported file names may seem a little bit less relevant,
they are actually relevant only as long as the files have not been installed
and I think for other libraries the names of files do no include any path
either, as can be seen e.g. in 


It is also worth mentionning that the PR makes the dynlink-related locations
consistent with those reported for, say, the Unix module and which do not
include path informations either. So backtraces only say `unix.ml` with
no path indication.

**Comment by lthls** [comment]
Line directives at the start of a file that look like `# 2 "foo.ml"` are useful for files that are copied or linked before they are compiled (typically, the architecture-specific files in `asmcomp/`).
Starting with 3 looks like a mistake, so I think this is worth fixing anyway.
Since the files affected by this PR are not copied or linked (at least as far as I could see), I think it is fine to remove the line directives. The new backtraces are not less correct than the old ones, I believe.

**Review by lthls — APPROVED** [review]

**Comment by shindere** [comment]
Thanks a lot, Vincent!
