### ISSUE TITLE
error during compilation with 4.05.0+flambda

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7714]
**Original bug ID:** 7714
**Reporter:** @c-cube
**Status:** resolved (set by @xavierleroy on 2018-06-20T14:12:21Z)
**Resolution:** fixed
**Priority:** normal
**Severity:** minor
**Platform:** linux
**Version:** 4.05.0
**Fixed in version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** middle end (typedtree to clambda)
**Monitored by:** @nojb @gasche

## Bug description

I've got a compilation error in flambda when I compile the benchmarks of containers:

> >> Fatal error: Missing renaming for specialised argument of a function being duplicated but not directly applied: add_list_/473936 -> add_list_/473334(= 
(move_within_set_of_closures
  CCHashTrie.add_list__surrogate/3068 <-- CCHashTrie.add_list_/811
  (closure = add_list_/473937))).

See attached log of the build failure for more details. I've got the same error in 4.06.0+flambda.

## Steps to reproduce

git clone https://github.com/c-cube/ocaml-containers
cd ocaml-containers
git checkout 7df23d0ccaf9e9d36455f8ca1a2db959e6e1f868
opam install jbuilder gen sequence qcheck benchmark
make benchs

## File attachments

- [error.txt](https://gist.githubusercontent.com/vicuna/af715c0deece72f9195f5d0751332aaa/raw/5aaeaa0c8d1b73bfd9ff3d74a7978536a128aa2a/error.txt)

**Comment by vicuna** [comment]
**Comment author:** @lpw25

We've seen this bug once at Janestreet. There is a fix for it mixed in with the changes in:

  https://github.com/ocaml/ocaml/pull/1343

Xavier Clerc was working on a stand-alone PR for it the other day, so there should be a fix merged pretty soon.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Can you please confirm this has been fixed and in which version?  (4.06, 4.07?)

**Comment by vicuna** [comment]
**Comment author:** @nojb

I confirm this is NOT fixed in 4.06.1.

Could not get the repro instruction to work with 4.07, so could not check if it is fixed there or not.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

That PR was merged in 4.07. So hopefully it is fixed there.
