### PR TITLE
Fix #mod_use in toplevel

### LINKED ISSUE #9455: 4.11.0~dev breaks use of topfind
When using 4.11.0~dev, trying to `opam install topkg` (or anything else using topfind) seems to break:

```
#=== ERROR while compiling topkg.1.0.1 ========================================#
# context     2.0.4 | macos/x86_64 | ocaml-variants.4.11.0+trunk | file:///Users/avsm/src/git/ocaml/opam-repository
# path        ~/.opam/devc2/.opam-switch/build/topkg.1.0.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pkg-name topkg --dev-pkg false
# exit-code   2
# env-file    ~/.opam/log/topkg-34480-60c5c2.env
# output-file ~/.opam/log/topkg-34480-60c5c2.out
### output ###
# [...]
# File "src/topkg_main.ml", line 7, characters 5-17:
# 7 | open Topkg_result
#          ^^^^^^^^^^^^
# Error: Unbound module Topkg_result
# File "src/topkg.ml", line 9, characters 8-20:
# 9 | include Topkg_result
#             ^^^^^^^^^^^^
# Error: Unbound module Topkg_result
# File "./pkg/pkg.ml", line 27, characters 5-10:
# 27 | open Topkg
#           ^^^^^
# Error: Unbound module Topkg
```

(I've not had a chance to bisect this further, but figured it's a serious enough regression to open up an issue early).

### PR DESCRIPTION
**Pull request by dra27**
Regression from #9283. Fixes #9455.

This is an absolute show-stopper for 4.11!

### CODE REVIEW

**Comment by Octachron** [comment]
It sounds like it would be a good idea to have test?

**Comment by dra27** [comment]
I'm just about to push it!

**Comment by dra27** [comment]
That test definitely fails on `trunk`

**Review by gasche — COMMENTED** [review]
Nice catch!

Some minor questions/remarks:
- there is another use of `false` in `use_output`, is that one correct?
- could we maybe use a labelled argument? (non-labelled boolean are a code smell as their call-sites are unreadable)
- I believe that `wrap_mod` was the right spelling, not `wrap_mode`, as I think "mod" refers to "module" here.

**Comment by gasche** [comment]
(But maybe `wrap_mod` could be renamed into `wrap_in_module` to avoid the confusion completely.)

**Comment by dra27** [comment]
Actually, the typo was the other way around - @diml mistyped `wrap_mod` which is the actual argument name. It reads to me as though Wojciech intended "wrap module" in 2012 when he added `#mod_use`.

I agree that a labelled argument or renaming would be better, but that code was fine for 8 years prior to being poked for a new feature - and the toplevel is getting a lot of attention elsewhere at the moment, anyway.

The use of `false` in `#use_output` is correct - otherwise it'll create an illegal module called `(stdin)`, I think.

**Comment by gasche** [comment]
Yes, our comments on wrap_mod agree. (Although I see why it's confusing that I'm commenting on the diff from the *other* PR). Personally I would prefer to improve the code now that there was a bug, instead of waiting for the next bug. I will push a labeling commit.

**Comment by avsm** [comment]
I can confirm that a30e621 fixes the various topfind compilation issues I saw.

**Review by gasche — APPROVED** [review]
Approving the PR. The code looks sensible, the regression is confirmed to be fixed.

**Comment by gasche** [comment]
@dra27 I will let you decide if/when to merge given that I was the last to push a commit.

**Comment by ghost** [comment]
PR looks good to me too!

**Comment by dra27** [comment]
Thanks @diml - let's do it!
