### PR TITLE
Add definition of cpu_relax for RISC-V

### PR DESCRIPTION
**Pull request by nojb**
The macro `__riscv` is documented here: https://github.com/riscv-non-isa/riscv-c-api-doc/blob/master/riscv-c-api.md#preprocessor-definitions

Not really sure how to test this, but I guess that running the testsuite should be enough. Will report back here once it is complete.

### CODE REVIEW

**Comment by kayceesrk** [comment]
Running the test suite should be sufficient. There are a number of uses of `cpu_relax` in the testsuite. We will know whether the code compiles and runs.

**Comment by nojb** [comment]
Firstly, the initial attempt wasn't good enough:
```
runtime/caml/platform.h: Assembler messages:
runtime/caml/platform.h:43: Error: unrecognized opcode `pause'
```
The Linux kernel uses this: https://github.com/torvalds/linux/blob/f0c4d9fc9cc9462659728d168387191387e903cc/arch/riscv/include/asm/vdso/processor.h#L24-L29

So I replaced the definition with
```c
/* Encoding of the pause instruction */
__asm__ volatile (".4byte 0x100000F");
```
and this seems to work (testsuite passes).

Secondly: there were some changes in `trunk` that had not been ported over to #11418, so in fact the RISC-V native backend is disabled in `trunk` at the moment. I made the needed tweaks in this PR (testsuite passes).

@kayceesrk do you mind doing a formal review of this PR? Thanks!

**Comment by gasche** [comment]
I hear that `pause` (when supported by the assembler) is defined as an alias for `fence w,0`, which is nicer to read than your encoded version?

**Comment by nojb** [comment]
> I hear that `pause` (when supported by the assembler) is defined as an alias for `fence w,0`, which is nicer to read than your encoded version?

Indeed. I'm running the testsuite with this change and, if it passes, will push it here.

**Comment by nojb** [comment]
> > I hear that `pause` (when supported by the assembler) is defined as an alias for `fence w,0`, which is nicer to read than your encoded version?
> 
> Indeed. I'm running the testsuite with this change and, if it passes, will push it here.

Unfortunately, it doesn't seem to work: 
```
runtime/caml/platform.h: Assembler messages:
runtime/caml/platform.h:44: Error: illegal operands `fence w,0'
```

**Comment by gasche** [comment]
I tested that it works on Clang starting with 9.0 godbolt: <https://godbolt.org/z/5q6xsaTfv>. I suppose that you are using a different assembler that does not support `0` as the second operand (this is the empty set of `iorw` flags, and it was never used in practice before the hint was added). Oh well.

**Comment by nojb** [comment]
> I tested that it works on Clang starting with 9.0 godbolt: https://godbolt.org/z/5q6xsaTfv. I suppose that you are using a different assembler that does not support `0` as the second operand (this is the empty set of `iorw` flags, and it was never used in practice before the hint was added). Oh well.

I'm using the `gcc` distributed with the `riscv64/ubuntu` [Docker image](https://hub.docker.com/r/riscv64/ubuntu/). It shows:
```
root@cb883641715b:/# gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@cb883641715b:/# cat fence.c
int foo(){
    asm volatile ("fence w,0");
    return 0;
}
root@cb883641715b:/# gcc -c fence.c
fence.c: Assembler messages:
fence.c:2: Error: illegal operands `fence w,0'
root@cb883641715b:/#
```
However, the same version on Godbolt seems to work: https://godbolt.org/z/c8E89cTx3...

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  Let's merge and then we'll get more feedback from CI.

**Comment by nojb** [comment]
Thanks!

**Comment by xavierleroy** [comment]
CI results look good overall, except for a failure on tests/lib-runtime-events/test_instrumented.ml:
```
> File "caml_startup", line 1:
> Error: Cannot find file libasmruni.a
```
How comes the instrumented runtime is not built, yet the test is run?

**Comment by nojb** [comment]
> CI results look good overall, except for a failure on tests/lib-runtime-events/test_instrumented.ml:

I hadn't seen this because the instrumented runtime _is_ compiled when using the Docker image. In any case, the test indeed should only be executed if the instrumented runtime is available: #11711

**Comment by shindere** [comment]
Thanks!

Feel free to merge this. From a semantic pointof view, it would make
more sense to me to have `* instrumented-runtime` as the first line and
then only the include and assignment statements, because those make real
sense only if the `instrumented-runtime` test passes.
