### PR TITLE
#10450: restore support for %apply and %revapply with non-translucid types

### LINKED ISSUE #10450: [4.13 bug] %apply externals require an arrow type as first argument regardless of the actual type
The following test case fails with OCaml 4.13 but worked perfectly before:
```
module M : sig
  type t
  val empty : t
end = struct
  type t = unit -> unit
  let empty () = ()
end

external test : M.t -> unit -> unit = "%apply"

let () = test M.empty ()
```
```
$ ocamlc test.ml
File "test.ml", line 11, characters 14-21:
11 | let () = test M.empty ()
                   ^^^^^^^
Error: This expression has type M.t
       This is not a function; it cannot be applied.
```
`M.t` is an abstract type but internally a function, which to me should be valid. However OCaml 4.13 somehow treats it as a function and rejects this code with a rather cryptic error message.

Looking into the PRs merged in 4.13 so far, it looks like this was introduced in https://github.com/ocaml/ocaml/pull/10081 (cc @alainfrisch @garrigue)

### PR DESCRIPTION
**Pull request by Octachron**
The new special typing rules in 4.13 for `%apply` and `%revapply` are only guaranteed to work when the types of the external values are exactly `('a -> 'b) -> 'a -> 'b` and `'a -> ('a->'b) -> 'b` respectively.

This PR ensures that when the types of the external do not match those expected types,
the standard typing rule is applied.

This restores support for various instances of
```ocaml
type f type x type y
external (@@): f -> x -> y = "%apply"
```

close #10450

### CODE REVIEW

**Review by kit-ty-kate — APPROVED** [review]
I've tested this PR backported to the `4.13` branch it seems to work pretty well on the original issue https://github.com/ocaml/ocaml/issues/10450. `bap-core-theory` was able to build without any issue or modification. Thanks a lot! :tada:

**Comment by Octachron** [comment]
If possible I would like to have a fix for #10450 in the first 4.13 beta to avoid a change of behavior during the beta. The code itself can be updated later (the current restriction on the special typing rule on `|>` and `@@` is partially syntactic and stricter than needed and could be improved for instance). 
Is there anyone that could review this PR (gentle ping to @lpw25 , @garrigue , @gasche , @trefis)?

**Review by trefis — APPROVED** [review]
Not the most readable condition, but it does seem correct.

File: typing/typecore.ml [hunk 1]
```diff
@@ -2738,6 +2738,26 @@ let rec is_inferred sexp =
   | Pexp_ifthenelse (_, e1, Some e2) -> is_inferred e1 && is_inferred e2
   | _ -> false
 
+
+(* check if the type of %apply or %revapply matches the type expected by
+   the specialized typing rule for those primitives.
+*)
+let translucid_apply_prim ~rev typ =
```
Comment (lpw25) [inline typing/typecore.ml]: This name is a bit opaque. Maybe just `check_apply_prim_type`. Also having a type:
```ocaml
type apply_prim =
  | Apply
  | Revapply
```
and using it in place of the `rev` parameter would probably make the code slightly clearer.

**Review by lpw25 — APPROVED** [review]
Looks good.

File: typing/typecore.ml (hunk 1 above)
Comment (Octachron) [reply typing/typecore.ml]: Being extra-explicit on this very ad-hoc function function seems like a good idea.

**Comment by Octachron** [comment]
Thanks @trefis and @lpw25  for the timely review!
