### PR TITLE
Refactor the initialization of bytecode threading (trunk version)

### LINKED ISSUE #11358: 4.14 branch fails to build with GCC 12.1
It looks like the latest release of GCC 12.1 triggers an additional warning that makes the build fail on the 4.14 branch:

```
gcc -c -O2 -fno-strict-aliasing -fwrapv -pthread -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -g  -D_FILE_OFFSET_BITS=64 -DCAML_NAME_SPACE  -DCAMLDLLIMPORT=  -o interp.b.o interp.c
interp.c: In function ‘caml_interprete’:
interp.c:253:21: error: storing the address of local variable ‘lbl_ACC0’ in ‘caml_instr_base’ [-Werror=dangling-pointer=]
  253 |     caml_instr_base = Jumptbl_base;
      |                     ^
interp.c:51:26: note: ‘lbl_ACC0’ declared here
   51 | #  define Instruct(name) lbl_##name
      |                          ^~~~
interp.c:323:5: note: in expansion of macro ‘Instruct’
  323 |     Instruct(ACC0):
      |     ^~~~~~~~
In file included from interp.c:25:
caml/fix_code.h:38:15: note: ‘caml_instr_base’ declared here
   38 | extern char * caml_instr_base;
      |               ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by xavierleroy**
Use a function `caml_init_thread_code` instead of exposing global variables `caml_instr_table` and  `caml_instr_base`.

This should silence the GCC 12 "dangling-pointer" warning.

Fixes: #11358

### CODE REVIEW

File: runtime/interp.c [hunk 1]
```diff
@@ -270,8 +270,7 @@ value caml_interprete(code_t prog, asize_t prog_size)
       (char *) raise_unhandled_code + sizeof(raise_unhandled_code),
       DIGEST_IGNORE, NULL);
 #ifdef THREADED_CODE
-    caml_instr_table = (char **) jumptable;
-    caml_instr_base = Jumptbl_base;
+    caml_init_thread_code(jumptable, Jumptbl_base);
```
Comment (gasche) [inline runtime/interp.c:273]: I wondered why the initialization function takes `void*` pointers instead of `char*` pointers. `jumptable` is defined as `void*`, but `Jumptbl_base` is currently defined as `char*` (so it is cast back and forth). According to the Gcc documentation, label-as-values really have type `void*`. In `fix_code.c` you use `char *` to be able to do pointer arithmetic.

I think the two following approaches would be slightly more consistent than the current one:
- keep everything as `void *` in interp.c, and `char *` in fix_code.c, which a cast in `caml_init_thread_code` (so: drop the `char *` casts in the Jumptbl_base definition)
- keep everything as `void *` everywhere, and cast right before doing the pointer substraction (so: same as above, plus changes to `fix_code.c`)

**Review by gasche — APPROVED** [review]
Looks fine. See minor comment on pointer types.

File: runtime/interp.c (hunk 1 above)
Comment (xavierleroy) [reply runtime/interp.c:273]: > I think the two following approaches would be slightly more consistent than the current one:

OK for approach 1.  However , `jumptbl_base` (lowercase) in interp.c must remain at type `char *`.
