### PR TITLE
cross-compilation: add missing errno.h include for error constants

### LINKED ISSUE #14883: Windows cross-compilation fails to build with older mingw32-gcc versions
Cross-compilation on Ubuntu 22/mingw32-gcc 10.3 targeting Windows fails with
```
link_win32.c: In function ‘caml_unix_link’:
link_win32.c:30:21: error: ‘ENOSYS’ undeclared (first use in this function)
   30 |     caml_unix_error(ENOSYS, "link", path2);
      |                     ^~~~~~
link_win32.c:30:21: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [../Makefile.otherlibs.common:171: link_win32.b.o] Error 1
make[2]: *** Waiting for unfinished jobs....
lockf_win32.c: In function ‘caml_unix_lockf’:
lockf_win32.c:73:23: error: ‘EINVAL’ undeclared (first use in this function)
   73 |       caml_unix_error(EINVAL, "lockf", Nothing);
      |                       ^~~~~~

```

I believe this was accidentally introduced by #13447 which removed the include of `errno.h` from these files, but this include is needed for the error constants.

This seems to go away on newer Ubuntu versions (which is why the cross-compilation CI in this repository doesn't catch it), possibly because a standard library header started transitively including errno.h. I temporarily changed the CI to use ubuntu-22.04 instead of ubuntu-latest here, which exposes the issue (and the trivial fix, which I am happy to contribute): https://github.com/WardBrian/ocaml/pull/1

### PR DESCRIPTION
**Pull request by WardBrian**
Would close #14883

As mentioned in that issue, this error only occurs on older compilers and thus is not spotted by the cross compilation CI here. See https://github.com/WardBrian/ocaml/pull/1 for CI runs that set the CI to run on an older distribution, causing it to fail, and the subsequent fix

### CODE REVIEW

**Review by smuenzel — APPROVED** [review]
`man 3 errno` says "The `<errno.h>` header file defines symbolic names for each of the possible error numbers that may appear in errno."

So I believe this implies that the inclusion of `errno.h` is required when referring to the symbolic names.

Thanks for the fix!

**Review by MisterDA — APPROVED** [review]
Obviously correct, thanks for catching and fixing my mistake!

**Comment by WardBrian** [comment]
Would this fall under the category of things that don't need a CHANGES entry? I can write one if not

**Comment by WardBrian** [comment]
I believe this would also be a good candidate to be cherry-picked into the 5.5 branch (not sure what the protocol is for this)

**Comment by MisterDA** [comment]
> I believe this would also be a good candidate to be cherry-picked into the 5.5 branch (not sure what the protocol is for this)

@Octachron

**Comment by Octachron** [comment]
As a backward compatibility fix, this sounds indeed reasonable to cherry-pick to 5.5 .

**Comment by Octachron** [comment]
Cherry-picked to 5.5 as 1315708; with an added Changes entry. The fix will be part of the 5.5.1 release in few weeks.
