### ISSUE TITLE
4.14 branch fails to build with GCC 12.1

### ISSUE THREAD

**Issue by Armael** [ocaml/ocaml#11358]
It looks like the latest release of GCC 12.1 triggers an additional warning that makes the build fail on the 4.14 branch:

```
gcc -c -O2 -fno-strict-aliasing -fwrapv -pthread -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -g  -D_FILE_OFFSET_BITS=64 -DCAML_NAME_SPACE  -DCAMLDLLIMPORT=  -o interp.b.o interp.c
interp.c: In function ‘caml_interprete’:
interp.c:253:21: error: storing the address of local variable ‘lbl_ACC0’ in ‘caml_instr_base’ [-Werror=dangling-pointer=]
  253 |     caml_instr_base = Jumptbl_base;
      |                     ^
interp.c:51:26: note: ‘lbl_ACC0’ declared here
   51 | #  define Instruct(name) lbl_##name
      |                          ^~~~
interp.c:323:5: note: in expansion of macro ‘Instruct’
  323 |     Instruct(ACC0):
      |     ^~~~~~~~
In file included from interp.c:25:
caml/fix_code.h:38:15: note: ‘caml_instr_base’ declared here
   38 | extern char * caml_instr_base;
      |               ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by dra27** [comment]
It's not at all clear to me why this part of trunk suppresses the error:

```diff
diff --git a/runtime/interp.c b/runtime/interp.c
index a59811c87..65d2ce029 100644
--- a/runtime/interp.c
+++ b/runtime/interp.c
@@ -20,6 +20,7 @@
 #include "caml/alloc.h"
 #include "caml/backtrace.h"
 #include "caml/callback.h"
+#include "caml/codefrag.h"
 #include "caml/debugger.h"
 #include "caml/fail.h"
 #include "caml/fix_code.h"
@@ -248,9 +249,17 @@ value caml_interprete(code_t prog, asize_t prog_size)
 #endif

   if (prog == NULL) {           /* Interpreter is initializing */
+    static opcode_t raise_unhandled_code[] = { ACC, 0, RAISE };
+
+    caml_register_code_fragment(
+      (char *) raise_unhandled_code,
+      (char *) raise_unhandled_code + sizeof(raise_unhandled_code),
+      DIGEST_IGNORE, NULL);
 #ifdef THREADED_CODE
     caml_instr_table = (char **) jumptable;
     caml_instr_base = Jumptbl_base;
+    caml_thread_code(raise_unhandled_code,
+                     sizeof(raise_unhandled_code));
 #endif
     return Val_unit;
   }
```

**Comment by Octachron** [comment]
The GCC warning seems to be at best a false positive, or even a bug in GCC? The label address `&&lab_ACC0` is not the address of a local variable and as far as I understand [gcc documentation](https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html) states that this use case is fine.

**Comment by xavierleroy** [comment]
On the one hand, the GCC warning seems to miss the fact that it's a label-as-value, not the address of a local variable.  On the other hand, storing a label in a global variable is dangerous too, as it makes it possible to jump to this label from another function.  So the warning can be legitimate but poorly worded in this case.

At any rate, we need to turn this warning off for interp.c if threaded code is being used.

**Comment by dra27** [comment]
I've [reported it to GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106080) - if the warning is intended, the text probably wants clarifying and it ought to being triggered on `trunk` too.

**Comment by dra27** [comment]
Given that this doesn't affect trunk and doesn't affect previous releases, I suggest we leave this open and wait and see what happens on the GCC side?

**Comment by xavierleroy** [comment]
Yes, let's wait and see.  I can also think of another way to write this part of interp.c that should silence the warning.

**Comment by dra27** [comment]
This is already affecting precheck for the 4.14 branch (the Fedora worker has GCC 12.1.1). This does work (for, I think, a C99-compliant somewhat loose definition of work):
```diff
--- a/runtime/caml/fix_code.h
+++ b/runtime/caml/fix_code.h
@@ -36,6 +36,7 @@ int caml_is_instruction (opcode_t instr1, opcode_t instr2);
 #ifdef THREADED_CODE
 extern char ** caml_instr_table;
 extern char * caml_instr_base;
+void caml_init_instr_base (uintptr_t);
 void caml_thread_code (code_t code, asize_t len);
 #endif

--- a/runtime/fix_code.c
+++ b/runtime/fix_code.c
@@ -85,6 +85,11 @@ void caml_fixup_endianness(code_t code, asize_t len)
 char ** caml_instr_table;
 char * caml_instr_base;

+void caml_init_instr_base(uintptr_t base)
+{
+  caml_instr_base = (char *)(void *)base;
+}
+
 static int* opcode_nargs = NULL;
 int* caml_init_opcode_nargs(void)
 {
--- a/runtime/interp.c
+++ b/runtime/interp.c
@@ -250,7 +250,7 @@ value caml_interprete(code_t prog, asize_t prog_size)
   if (prog == NULL) {           /* Interpreter is initializing */
 #ifdef THREADED_CODE
     caml_instr_table = (char **) jumptable;
-    caml_instr_base = Jumptbl_base;
+    caml_init_instr_base((uintptr_t)(void *)Jumptbl_base);
 #endif
     return Val_unit;
   }
```

is it worth doing this or something similar quickly just to restore Jenkins testing for the 4.14 branch? (or at least partly restore - there's an OpenBSD problem as well).

**Comment by xavierleroy** [comment]
Give me a few days to think about a reasonable fix.  ("Reasonable" = "removes the warning" + "improves the structure of the code").

**Comment by dra27** [comment]
> "Reasonable" = "removes the warning" + "improves the structure of the code"

Indeed - the only word to describe my proposal is “dirty”!

**Comment by xavierleroy** [comment]
Here is a proposal: #11378 #11379 .  I checked with GCC 12.1 under Fedora and the warning doesn't trigger.

The fix follows @dra27's approach (hide the assignment in a function) but seizes the opportunity to make the variables `caml_instr_table` and `caml_instr_base` local to the `fix_code.c` module.
