### ISSUE TITLE
Test output-complete-obj fails with spacetime

### ISSUE THREAD

**Issue by gretay-js** [ocaml/ocaml#9093]
The test in `testsuite/tests/output-complete-obj/test` fails with 
```
ld: cannot find -lunwind
ld: cannot find -lunwind-x86_64
File "caml_startup", line 1:
Error: Error during linking
```
compiler configured with --enable-spacetime
target: amd64 linux target 
ocaml compiler versions 4.08 through trunk

I can compile programs with spacetime, and I do have libunwind on the system. Am I missing something, or could it be a problem with the test @shindere  @nojb ?  It's the only test that uses ${mkexe} variable.

**Comment by nojb** [comment]
Hello, I tried to reproduce but the test passed on the spacetime-enabled `trunk` on OS X.

**Comment by gretay-js** [comment]
thanks for checking it! I'll try to figure out why it isn't working on my centos box.

**Comment by dra27** [comment]
It appears to be working on my CentOS 7.7 and Ubuntu 19.04 boxes

**Comment by gretay-js** [comment]
Thank you for confirming. Something must be missing in my setting...

**Comment by gretay-js** [comment]
@dra27 confirmed offline that this test fails on centos when libunwind is available, which requires libunwind-devel package and headers to be installed.

**Comment by shindere** [comment]
Greta Yorsh (2019/11/05 07:34 -0800):
> The test in `testsuite/tests/output-complete-obj/test` fails with
> ```
> ld: cannot find -lunwind
> ld: cannot find -lunwind-x86_64
> File "caml_startup", line 1:
> Error: Error during linking
> ```
> compiler configured with --enable-spacetime

For me, trunk with spacetime enabled does not even compile:

```
minor_gc.c:520:9: error: ‘caml_young_ptr’ undeclared (first use in this function)
```

and I tried with and without libunwind.

Did you see this error @gretay-js?

**Comment by gretay-js** [comment]
@shindere Yes, it's been recently broken by merge 92bfafc1ac2986eef730009af90bfcab71052a22  of PR #8805, but that's a separate problem. :)

**Comment by shindere** [comment]
Greta Yorsh (2019/11/11 00:47 -0800):
> @shindere Yes, it's been recently broken by merge
> 92bfafc1ac2986eef730009af90bfcab71052a22  of PR #8805, but that's a
> separate problem. :)

Sure, but that problem you mention makes the other one impossible to
reproduce anyway, so is there already somebody working on that second
problem, or not?

**Comment by gretay-js** [comment]
Yes, I mentioned this problem to @stedolan. In the meantime, I used trunk before that commit to work on it.

**Comment by shindere** [comment]
Any progress on this?

How important is it to actually fix the problem reported here?

Shall we close this issue and reopen it if the problem becomes really
crucial?

**Comment by xavierleroy** [comment]
Spacetime is gone (#9948), so this issue can be closed.
