### PR TITLE
Fix #9714 "Compilation failure in domain_state.h"

### LINKED ISSUE #9714: Compilation failure in `domain_state.h` for librairies with OCaml ≥ 4.10
Ha!

I think I’ve found a bug in OCaml! A real one ;-)
The bug was introduced in commit fc6f0284922621fc8717033a8d73b1134f1506ac and affects OCaml ≥ 4.10.
Pinging the contributors to this file: @kayceesrk, @Engil, and @dra27.

In Opam, we’re transitionning to [OCaml 4.10 for bootstrap][41000-bootstrap], and we’ve
had this issue in [Opam’s CI][CI]:

    c:\projects\opam\bootstrap\ocaml\lib\ocaml\caml\domain_state.h(49): error C2118: negative subscript

It comes from here:

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/domain_state.h#L47-L50

If the assertion fails, it emits an array of size -1 which the
compiler rejects.

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/domain_state.h#L28-L36

The structure is carefully crafted so that each of its elements are
aligned to an 8-bit boundary, meaning that no padding is inserted
*between* the elements.

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/misc.h#L93-L105

The `CAMLalign` is well defined to support most compilers; so we can
guess that all elements are aligned as expected, and no padding is
inserted *between* them.

However, this fails to take into account the padding that the compiler
may insert *at the end* of the structure. First mistake. Ref: [The Lost Art of Structure Packing, §4](http://www.catb.org/esr/structure-packing/#_padding). 

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/domain_state.h#L38-L43

`Domain_state_num_fields` counts the number of fields in the table.
The comparison with `Domain_state_num_fields * 8` can not be correct
if some fields are not 8 octects long. One only need to see that the
`domain_state.tbl` stores pointers, and they are not always 8
octets-long, especially on 32-bits architectures. Second mistake.

Now, to fix the assertion, we could loop over the fields, and keep
accumulate the sum of the sizes of each fields, and compare that with
the `caml_domain_state` structure, but again, we would miss the end
structure padding.

I think the best fix is to *pack* and *align* to the 8-bit boundary
the structure.
EDIT: and we could remove calls to `CAMLalign` and the static assertion.

So, with [GCC][GCC-attributes] we’re interested by the `packed`, `aligned`, and
`warn_if_not_aligned` attributes, but that wouldn’t be portable.
An alternative with pragmas that seems to be compatible across
compilers: [GCC][GCC-pragmas], [Clang][Clang-pragmas] (manpage is old but the feature should
still be present), and [MSVC][MSVC-pragmas].

```c
#pragma pack(push, 8)
typedef struct {
    // …
} caml_domain_state;
#pragma pack(pop)
```

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/misc.h#L93-L96

This statement puzzles me. Could the runtime use `offsetof` to get the
address of each member?

I hope I got the analysis right. What do you think?

-- Antonin

[41000-bootstrap]: https://github.com/ocaml/opam/pull/4242
[CI]: https://ci.appveyor.com/project/AltGr/opam/build/job/qenst562ctllutth#L6672
[GCC-attributes]: https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html#Common-Type-Attributes
[GCC-pragmas]: https://gcc.gnu.org/onlinedocs/gcc/Structure-Layout-Pragmas.html#Structure-Layout-Pragmas
[Clang-pragmas]: https://releases.llvm.org/3.4/tools/clang/docs/UsersManual.html#microsoft-extensions
[MSVC-pragmas]: https://docs.microsoft.com/en-us/cpp/preprocessor/pack?view=vs-2019

### PR DESCRIPTION
**Pull request by MisterDA**
Fix #9714 "Compilation failure in `domain_state.h`".

### CODE REVIEW

File: runtime/caml/misc.h [hunk 1]
```diff
@@ -98,6 +98,8 @@ CAMLdeprecated_typedef(addr, char *);
 #define CAMLalign(n) _Alignas(n)
 #elif defined(SUPPORTS_ALIGNED_ATTRIBUTE)
 #define CAMLalign(n) __attribute__((aligned(n)))
+#elif defined(__cplusplus) && (_MSC_VER >= 1900 || __cplusplus > 199711L)
```
Comment (xavierleroy) [inline runtime/caml/misc.h]: `alignas` is C++ 2011, if I'm not mistaken, so the test should be `__cplusplus >= 201103L`.

**Review by xavierleroy — COMMENTED** [review]
Thanks for the PR, which looks good to me.  One question below regarding C++ version numbers.

File: runtime/caml/misc.h (hunk 1 above)
Comment (xavierleroy) [reply runtime/caml/misc.h]: Also I would put this case above the `#elif defined(SUPPORTS_ALIGNED_ATTRIBUTE)` so that the C++-standard `alignas` implementation is preferred over the compiler-specific `__attribute__` implementation.

Comment (MisterDA) [reply runtime/caml/misc.h]: > `alignas` is C++ 2011, if I'm not mistaken, so the test should be `__cplusplus >= 201103L`.

You’re right, but there’s no new value between 199711L and 201103L. I’ll change the value, but the result is the same.

> Also I would put this case above the `#elif defined(SUPPORTS_ALIGNED_ATTRIBUTE)` so that the C++-standard `alignas` implementation is preferred over the compiler-specific `__attribute__` implementation.

Sure!

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  I assume this has been tested with MSVC in C++ mode?  Our CI testing will never test this configuration.

File: runtime/caml/misc.h (hunk 1 above)
Comment (dra27) [reply runtime/caml/misc.h]: [Stroustroup suggests `> 199711L` for detecting C++11](https://www.stroustrup.com/C++11FAQ.html#11) I have no idea whether there are actually an C++ compilers for which that would actually make a difference (just for the context of where the test was taken).

**Review by dra27 — APPROVED** [review]
LGTM! MSVC has had `offsetof` (in its traditional `#define offsetof(s,m) (size_t)&(((s *)0)->m)` form) since the dawn of time.

@Octachron - I'd like the fix for MSVC in 4.10.1, however the change to the assertion changes the size of `caml_domain_state`; it also alters the behaviour for C++ compilers which aren't necessarily broken. Can this be risked, or should a more limited version with just the change to `misc.h` guarded for MSVC only go into 4.10? Similarly for 4.11, unless we expect another beta? My nervousness is that opam is a C++ consumer of the OCaml headers...

**Comment by Octachron** [comment]
If I understand correctly, this change should only affect users that were hardcoding the exact size of the internal domain_stat `struct`, isn't? This seems fine to break in a beta.

For 4.11.0, we can start by checking if the opam and the opam ecosystem works fine with the fix, and if it is the case, we can have another beta next week.

For 4.10.1, I would rather make the update path as transparent as possible. Thus, it would make sense to me to split the patch to keep only the necessary MSVC patch.

Another point, should the fix be shared with multicore OCaml to avoid diverging runtimes?

**Comment by dra27** [comment]
Thanks, @Octachron - I'll do that after this is merged.

@MisterDA - do you want to push a `Changes` entry? It wants to go in the `OCaml 4.10 maintenance branch` in the `Runtime System` section.

@xavierleroy - we could, and possibly should, test C++ at some point (though it doesn't have to be here). We only need enough C++ detection for AppVeyor/Travis/Jenkins to detect a C++ compiler for the testsuite and then essentially compile the existing "calling OCaml from C" tests using C++, or another simple `print_endline "Hello C++"` OCaml program with a C++ `main` which includes _all_ of the runtime's header files. That might be beneficial for things like #9523 as well.

**Comment by dra27** [comment]
I had an offline discussion with @ctk21 about the multicore question - this will be automatically merged in when they rebase to 4.11, which is easier for them than lots of parallel PRs.

File: runtime/caml/misc.h (hunk 1 above)
Comment (xavierleroy) [reply runtime/caml/misc.h]: Stroustrup's text reads like it was written before the exact value of `__cplusplus` for C11 was determined.

Not being a C++ expert, I cannot guess that `__cplusplus > 199711L` means C++11 or later, while I can guess that `__cplusplus >= 201103L` means this.

**Comment by Octachron** [comment]
What is the status of this PR?

**Comment by dra27** [comment]
Sorry - I didn't notice the Changes entry got pushed yesterday!

**Comment by dra27** [comment]
Full fix pushed to 4.11 and the partial fix (for MSVC-only) pushed to 4.10

**Comment by Octachron** [comment]
Thanks!
