### ISSUE TITLE
non-principal disambiguation succeeds in 4.07, fails in 4.08

### ISSUE THREAD

**Issue by trefis** [ocaml/ocaml#8551]
FTR: I don't think there is anything we want to do, I'm just recording the change.

## Reproduction

- `a.ml`: `type t = A | B`
- `b.ml`:
  ```ocaml
  type t = A.t
  
  let rec test () =
    match (assert false : t) with
    | exception _ -> A
    | A -> test ()
    | t -> t
  ```

This builds fine with 4.07.
But fails with the error below on 4.08, trunk, or 4.07 when passing `-principal`:
```
File "./b.ml", line 5, characters 19-20:
5 |   | exception _ -> A
                       ^
Error: Unbound constructor A
```

## Proposed explanation

If you replace the `exception _` branch by a normal one, this was already failing with 4.07. I guess the change is due to the fact that exception cases were typed later, so we already knew what type to expect for the branch.

**Comment by trefis** [comment]
To clarify: `exception` patterns are now "normal" patterns, and so are typed in order.
