### ISSUE TITLE
usability issue: no error when opening an alias to a missing module

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#9695]
Apparently `open X` does not complain if `X` is an alias to an unknown module and `-no-alias-deps` is used -- it behaves as if it was just ignored. This looks like a usability bug in the compiler to me:

```ocaml
module A = MissingModule
let () = let open A in x

(* $ ocamlc -no-alias-deps test.ml
File "test.ml", line 2, characters 23-24:
2 | let () = let open A in x
                           ^
Error: Unbound value x
*)
```

```ocaml
module A = MissingModule
let () = let open A in ()
(* compiles just fine with -no-alias-deps *)
```

(Note: `open A` at the toplevel behaves in the same surprising way.)

I hit this issue while working on the compiler itself: I had an `open Nativeint`, and below it used the function `to_int`; I would get an "Unbound value `to_int`" because the Makefile .depend file was stale and nativeint was not compiled yet.

This appears to be a regression: OCaml 4.03 to 4.05 (but not later version) reports the following error on both examples:

```
File "test.ml", line 2, characters 18-19:
Error: This is an alias for module MissingModule, which is missing
```

OCaml 4.02.1 (`-no-alias-deps` was introduced in 4.02) reports a worse message:

```
File "test2.ml", line 2, characters 5-6:
Error: This module is not a structure; it has type (module MissingModule)
```

**Comment by xavierleroy** [comment]
That explains the mysterious failure in #9691.  I've never been a fan of `let open in`, but still, this needs to be fixed.

**Comment by garrigue** [comment]
Found the culprit: this is the function `Env.get_components` that returns an empty structure when `get_components_res` returns an error.
This was introduced by @lpw25 in ocaml 4.06.
@lpw25, can you explain the rationale behind that?

**Comment by gasche** [comment]
The change was introduced in #1223, as part of changes to be more robust against missing `.cmi` files or working without loading `.cmi` files.

Let me include the following timely quote from @lpw25 in that PR as a subtle hint:

> I agree this whole thing is fragile, but I'm not too worried as I have a complete reimplementation of short-paths that removes it and I'm hoping to get that into the compiler before too long (it's already being used on merlin's development branch but I'd like to tidy it up and document it before submitting it to the compiler -- which will probably be after the 4.06 freeze).

**Comment by lpw25** [comment]
I don't think #1223 changes the behaviour here -- it certianly isn't meant to. 

`components_of_module_maker` used to return an empty struct in some cases. Now it returns `None` in those cases instead and `None` is then converted to an empty struct outside of the caching logic.

So I think you'll need to git blame further back to find the real culprit.

**Comment by gasche** [comment]
I could confirm that the commit before #1223 still has this problem. Bisect in progress.

**Comment by gasche** [comment]
Bisection shows that the issue appeared in @alainfrisch's commit https://github.com/ocaml/ocaml/commit/3d037367a28a590876c8361a620e3402c108a36b, which is part of #834.

**Comment by gasche** [comment]
The following part of the patch may be causing the issue:

```diff
let rev env_from_summary sum subst =
[...]

      | Env_open(s, path) ->
          let env = env_from_summary s subst in
          let path' = Subst.module_path subst path in
-          let md =
-            try Env.find_module path' env
-            with Not_found ->
-              raise (Error (Module_not_found path'))
-          in
-          Env.open_signature Asttypes.Override path'
-            (extract_sig env md.md_type) env
+          begin match Env.open_signature Asttypes.Override path' env with
+          | Some env -> env
+          | None -> assert false
+          end
```

**Comment by garrigue** [comment]
But why would we be using `env_from_summary` here ?
I thought it was only used for the debugger.

**Comment by gasche** [comment]
This was only a wild guess from quickly looking at the patch, it may very well be wrong and I would recommend giving it a deeper look. (Actually I removed that comment shortly after sending it because I found the guess too wild, even to my taste!)

**Comment by garrigue** [comment]
Ok, @alainfrisch  switched to use `get_components` in `open_signature`. That seems to be the culprit.
Probably should check first that the module is available.
