### ISSUE TITLE
Compilation failure in `domain_state.h` for librairies with OCaml ≥ 4.10

### ISSUE THREAD

**Issue by MisterDA** [ocaml/ocaml#9714]
Ha!

I think I’ve found a bug in OCaml! A real one ;-)
The bug was introduced in commit fc6f0284922621fc8717033a8d73b1134f1506ac and affects OCaml ≥ 4.10.
Pinging the contributors to this file: @kayceesrk, @Engil, and @dra27.

In Opam, we’re transitionning to [OCaml 4.10 for bootstrap][41000-bootstrap], and we’ve
had this issue in [Opam’s CI][CI]:

    c:\projects\opam\bootstrap\ocaml\lib\ocaml\caml\domain_state.h(49): error C2118: negative subscript

It comes from here:

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/domain_state.h#L47-L50

If the assertion fails, it emits an array of size -1 which the
compiler rejects.

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/domain_state.h#L28-L36

The structure is carefully crafted so that each of its elements are
aligned to an 8-bit boundary, meaning that no padding is inserted
*between* the elements.

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/misc.h#L93-L105

The `CAMLalign` is well defined to support most compilers; so we can
guess that all elements are aligned as expected, and no padding is
inserted *between* them.

However, this fails to take into account the padding that the compiler
may insert *at the end* of the structure. First mistake. Ref: [The Lost Art of Structure Packing, §4](http://www.catb.org/esr/structure-packing/#_padding). 

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/domain_state.h#L38-L43

`Domain_state_num_fields` counts the number of fields in the table.
The comparison with `Domain_state_num_fields * 8` can not be correct
if some fields are not 8 octects long. One only need to see that the
`domain_state.tbl` stores pointers, and they are not always 8
octets-long, especially on 32-bits architectures. Second mistake.

Now, to fix the assertion, we could loop over the fields, and keep
accumulate the sum of the sizes of each fields, and compare that with
the `caml_domain_state` structure, but again, we would miss the end
structure padding.

I think the best fix is to *pack* and *align* to the 8-bit boundary
the structure.
EDIT: and we could remove calls to `CAMLalign` and the static assertion.

So, with [GCC][GCC-attributes] we’re interested by the `packed`, `aligned`, and
`warn_if_not_aligned` attributes, but that wouldn’t be portable.
An alternative with pragmas that seems to be compatible across
compilers: [GCC][GCC-pragmas], [Clang][Clang-pragmas] (manpage is old but the feature should
still be present), and [MSVC][MSVC-pragmas].

```c
#pragma pack(push, 8)
typedef struct {
    // …
} caml_domain_state;
#pragma pack(pop)
```

https://github.com/ocaml/ocaml/blob/b212928e740388d55ebce1978541e02db77cbb20/runtime/caml/misc.h#L93-L96

This statement puzzles me. Could the runtime use `offsetof` to get the
address of each member?

I hope I got the analysis right. What do you think?

-- Antonin

[41000-bootstrap]: https://github.com/ocaml/opam/pull/4242
[CI]: https://ci.appveyor.com/project/AltGr/opam/build/job/qenst562ctllutth#L6672
[GCC-attributes]: https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html#Common-Type-Attributes
[GCC-pragmas]: https://gcc.gnu.org/onlinedocs/gcc/Structure-Layout-Pragmas.html#Structure-Layout-Pragmas
[Clang-pragmas]: https://releases.llvm.org/3.4/tools/clang/docs/UsersManual.html#microsoft-extensions
[MSVC-pragmas]: https://docs.microsoft.com/en-us/cpp/preprocessor/pack?view=vs-2019

**Comment by dra27** [comment]
The problem is a bug in VS 2015 either Update 2 or Update 3+ and specifically affects compilation in C++ mode. The issue is that the `declspec(align(8))` suddenly has to be put after the `struct foo` and before the `*` for all the struct pointer members. I ascertained it’s not affecting VS 2013 and earlier, so the simplest fix I think will be to use the C++ `alignas` when the header is read in C++ mode and _MSC_VER >= 1900

**Comment by xavierleroy** [comment]
It's hard to know whether the C compiler is at fault.  My viewpoint is that the alignment of a C struct should always divides evenly the size of the struct, even if some of the struct members have forced alignments.  This is what GCC does as far as I could figure out, and also what my CompCert C formalization does.  But this may not be absolutely necessary, and this report shows that MSVC takes a different interpretation.  (Yet I'm curious to know what happens with an array of `caml_domain_state` elements...)

The solution is to change the assertion, to `sizeof(caml_domain_state) <= (Domain_state_num_fields) * 8`.  This should be enough to detect cases of unwanted padding, yet support the "don't pad after the last member" approach of MSVC.

I'd rather avoid "packed" structs because they are poorly defined and excessively compiler-dependent.

**Comment by xavierleroy** [comment]
Thinking of it, another, more robust way to write the assertion:
```
typedef struct { 
 ...
 #include "domain_state.tbl" 
 CAMLalign(8) char end_of_domain_state;
 } caml_domain_state; 

CAML_STATIC_ASSERT(offsetof(caml_domain_state, end_of_domain_state) == Domain_state_num_fields * 8)
```
In other words: we don't care about the total size of the struct, but we care that the members before `end_of_domain_state` are spaced by 8.

**Comment by dra27** [comment]
@xavierleroy - I would put more fault on MSVC here. It processes the headers differently depending on whether the file is included from a .cpp file or a .c file - in particular, `__declspec(align(8)) struct caml__something * caml_something` works from a .c file (which is why we hadn’t seen it) but in a .cpp it either needs to be `alignas(8) struct caml__something * caml_something` or (weirdly) `struct caml__something __declspec(align(8)) * caml_something`

**Comment by dra27** [comment]
(Sorry for the unintended close)
The behaviour also suddenly changed in either Update 2 or Update 3 of VS2015 (the original release and Update 1 definitely work as expected)

For the assertion, I think it may have used other mechanisms before and then been converted for MSVC-support - however, if we engineer it so that the last member is always 8 bytes (I can’t see from my phone if it is already?), then the existing code should always work regardless of packing after the final member?

**Comment by xavierleroy** [comment]
> if we engineer it so that the last member is always 8 bytes (I can’t see from my phone if it is already?), then the existing code should always work regardless of packing after the final member?

Today the last member is a pointer, so 4 or 8 bytes.  There are few members that are always 8 bytes.  I'd rather put an artificial member last (like my suggested `end_of_domain_state`), but I agree it could be declared with an 8-byte type.

**Comment by xavierleroy** [comment]
Re: different meanings for `__declspec(align(8))`, this is unfortunate, but I can sympathize.  (CompCert did some back-and-forth too in how `__attribute__((aligned(8)))` (and other attributes) is to be parsed and attached to AST nodes, as the notation is inherently ambiguous.)  

I support using `alignas` in C++ 2011 and later, and `_Alignas` in C 2011 and later, since these keywords are standardized, and revert to `__declspec` or `__attribute__` only when the standard keywords are not available.

**Comment by xavierleroy** [comment]
One last thing: what happens if we wrap `domain_state.h` in `extern "C" { ... }` like several other headers do?

**Comment by dra27** [comment]
`extern "C"` appears to make no difference (it was the first thing I tried, being suspicious that it was a C++ problem)

**Comment by MisterDA** [comment]
Thanks for the explanations! I think my mistake was that I thought that `alignas(8)` meant aligning to the next *8-bit* boundary and not *8-byte*. This is why I thought that the intent was to pack the structure.
What if a member longer than 8 octets was included? The assertion would be wrong in that case.

**Comment by dra27** [comment]
The domain state consists of either pointers or things <= pointers - if something larger than 8 bytes had to be added, it would either be indirectly or with multiple fields. The reason is that the assembler generated both by ocamlopt and the assembler portions of the runtime need to be able to refer to fields by index

**Comment by xavierleroy** [comment]
> The domain state consists of either pointers or things <= pointers

Or double FP numbers (8 bytes, even on 32-bit platforms).

**Comment by MisterDA** [comment]
Are there no intent to port OCaml to a 128 bits platform (!!) or use other definitions of floats than ieee 754 (!)?
The occurrences of `8` could be replaced with a macro, something like `#define boundary (max(sizeof(void*), sizeof(double), sizeof(uintnat)))` to (perhaps) better carry the intent.
If the ordering of the elements in the domain state does not matter, we could add a comment to ensure that an 8 byte element be always last in the struct, but even that may not be possible: the commit introducing the domain state had only one pointer in it.
I find `end_of_domain_state` rather elegant and fool-proof.

**Comment by xavierleroy** [comment]
> Are there no intent to port OCaml to a 128 bits platform (!!) or use other definitions of floats than ieee 754 (!)?

Not at this time nor any time soon.  If the need arises much later, we could align every field on 16-byte boundaries.

> The occurrences of 8 could be replaced with a macro

The issue is that we need to compute the offsets of the domain_state members from assembly code, see for example https://github.com/ocaml/ocaml/blob/trunk/runtime/amd64.S#L115-L122

This is much easier if every member occupies the same number of bytes (currently, 8).

**Comment by stedolan** [comment]
> It's hard to know whether the C compiler is at fault. My viewpoint is that the alignment of a C struct should always divides evenly the size of the struct, even if some of the struct members have forced alignments.

Isn't your viewpoint implied by C? The compiler is not allowed to insert padding between array elements, so the alignment of a C struct must divide the size of the struct, so that the second element of an array of such structs is not misaligned.

**Comment by stedolan** [comment]
Is it possible that what was going wrong here is actually that MSVC in C++ mode is correctly aligning everything to 8 bytes, but is enforcing an even stronger alignment (16 or 32-bytes) for the whole structure? That would cause it to add extra padding at the end while not breaking 8-byte alignment anywhere. (If this is the case, then the patch in #9724 is indeed the right fix)

@MisterDA or @dra27: what actual value of `sizeof(caml_domain_state)` did you see?

**Comment by dra27** [comment]
Hang on, I'll dig the test program out - it was _number of elements which are not struct pointers_ * 8 + _number of elements which are struct pointers_ * 4

**Comment by dra27** [comment]
The smaller repro case I reduced it to is:

`fragment`
```c
#include <stdio.h>

typedef struct domain_state {
__declspec(align(8)) int caml_foo;
__declspec(align(8)) struct caml__roots_block * local_roots;
__declspec(align(8)) int * caml_bar;
__declspec(align(8)) int * caml_baz;
} caml_domain_state;

typedef struct domain_state2 {
__declspec(align(8)) int caml_foo;
struct caml__roots_block __declspec(align(8)) * local_roots;
__declspec(align(8)) int * caml_bar;
__declspec(align(8)) int * caml_baz;
} caml_domain_state2;

int main (int argc, char* argv[]) {
  printf("%s\n", argv[0]);
  printf("sizeof(caml_domain_state) = %d\n", sizeof(caml_domain_state));
  printf("sizeof(caml_domain_state2) = %d\n", sizeof(caml_domain_state2));
}
```
`main.c` & `main.cpp`
```c
#include "fragment"
```

and then obviously compiled with either `cl /nologo /Fefoo-c.exe main.c` or `cl /nologo /Femain-cpp.exe main.cpp`. With Visual Studio 2013:

```
C:\Users\DRA\Documents\Align>cl /nologo /Femain-c.exe main.c
main.c

C:\Users\DRA\Documents\Align>cl /nologo /Femain-cpp.exe main.cpp
main.cpp

C:\Users\DRA\Documents\Align>main-c
main-c
sizeof(caml_domain_state) = 32
sizeof(caml_domain_state2) = 32

C:\Users\DRA\Documents\Align>main-cpp
main-cpp
sizeof(caml_domain_state) = 32
sizeof(caml_domain_state2) = 32
```
with Visual Studio 2015 Update 3:
```
C:\Users\DRA\Documents\Align>cl /nologo /Femain-c.exe main.c
main.c

C:\Users\DRA\Documents\Align>cl /nologo /Femain-cpp.exe main.cpp
main.cpp

C:\Users\DRA\Documents\Align>main-c
main-c
sizeof(caml_domain_state) = 32
sizeof(caml_domain_state2) = 32

C:\Users\DRA\Documents\Align>main-cpp
main-cpp
sizeof(caml_domain_state) = 24
sizeof(caml_domain_state2) = 32
```

**Comment by MisterDA** [comment]
I tested the Opam bootstrap with the 4.10 branch and the alignas patch applied and can confirm that the patch fixes the bug in the context where it was found.
- [Opam patch](https://github.com/MisterDA/opam/commit/3de8ee39d428c4d346fe6ee4c5ab57317623e007)
- [OCaml branch](https://github.com/MisterDA/ocaml/tree/4.10-fix-domain-state)
- [Opam CI](https://ci.appveyor.com/project/MisterDA/opam/builds/33822113/job/qsy8j3lf99p3tvvl)

> with Visual Studio 2015 Update 3:

I uploaded the code in [godbolt](https://godbolt.org/z/pv2bg9).

**Comment by xavierleroy** [comment]
> Isn't your viewpoint implied by C? The compiler is not allowed to insert padding between array elements, so the alignment of a C struct must divide the size of the struct, so that the second element of an array of such structs is not misaligned.

For structs and unions, this property (alignof divides sizeof)  is what I've observed with every compiler and seen in formalizations of C and C++.  

Stranger things happen when nonstandard "increase alignment" mechanisms are used.  For example with GCC's "aligned" attribute:
```
typedef __attribute__((aligned(16))) int int4al16;   // has size 4 and alignment 16

int4al16 x;  // has size 4 and alignment 16
int4al16 t[2];  // is rejected: "error: alignment of array elements is greater than element size"
```

> Is it possible that what was going wrong here is actually that MSVC in C++ mode is correctly aligning everything to 8 bytes, but is enforcing an even stronger alignment (16 or 32-bytes) for the whole structure? 

I don't think it's allowed by the C++ standard, especially since this struct is Plain Old Data, hence obeys the same layout rules as in C.  But assuming it is allowed, this would be one more reason for not testing the size of the structure and use the approach in 
#9724 instead.

**Comment by stedolan** [comment]
Ah, I see. It hadn't occurred to me that a C compiler might use a weird alignment, and then just reject array types involving that type. Thanks for the explanations, all, and I agree that the fix in #9724 is the right one.
