### ISSUE TITLE
Wrong arity for builtin primitive "%identity"

### ISSUE THREAD

**Issue by rnd4222** [ocaml/ocaml#8660]
Following code are fails to compile under 4.08.0+beta3:
```
# external f : ('a -> 'b) -> ('a -> 'b) = "%identity";;
Error: Wrong arity for builtin primitive "%identity"
```
It's funny that defining alias for a function type compiles OK:
```
# type ('a, 'b) t = 'a -> 'b;;
type ('a, 'b) t = 'a -> 'b
# external f : ('a, 'b) t -> ('a, 'b) t = "%identity";;
external f : ('a, 'b) t -> ('a, 'b) t = "%identity
```

**Comment by nojb** [comment]
I don't think this is a bug. The notion of arity is syntactic, and the signature in question is parsed as `('a -> 'b) -> 'a -> 'b`, so the arity is 2, not 1.

Closing because I think this is the right behaviour, but feel free to re-open if you deem it necessary.

**Comment by rnd4222** [comment]
@nojb this notion of arity is neither semantic (because it works with type alias) nor syntactic (because adding parentheses doesn't change anything).
To me it doesn't look like well-formed notion of arity correctness.
It's hardly the "right behaviour", because such a difference between using function type vs alias (and impossibility to use it with function type) is at least unexpected.
I know that builtin primitives is not expected to be used outside of OCaml compiler, but some libraries using it anyway, and this change breaks it.
I can't reopen the issue. ~~Can you point me into any discussion of such a change?~~ It seems that #2015 was merged without much discussion on semantic of such a check.

**Comment by nojb** [comment]
> I know that builtin primitives is not expected to be used outside of OCaml compiler, but some libraries using it anyway, and this change breaks it.

This is right on; if you are using `external`s in a library you better know what you are doing. And if it breaks, you get to keep both pieces.

> @nojb this notion of arity is neither semantic (because it works with type alias) nor syntactic (because adding parentheses doesn't change anything).

Adding parentheses does not change anything in this case because `->` is right-associative.

> I can't reopen the issue. Can you point me into any discussion of such a change?

As you already discovered, this check was introduced in #2015.

**Comment by gasche** [comment]
If this is a regression compared to existing versions of OCaml, we may need to discuss whether this kind of code (1) was correctly supported by previous versions (or does it raise assert failures when used later, as the different-looking examples in bug reports #7408 and #7846?) and (2) is used in the wild for something useful (so it's a problem to regress there).

@rnd4222, do you have a use-case for this feature, or a pointer to a specific codebase that is broken by the change?

**Comment by rnd4222** [comment]
@gasche clarity [uses](https://github.com/IndiscriminateCoding/clarity/blob/master/lib/types/reader.ml#L16) identity for zero-cost conversion to/from abstract type, represented as a function.

**Comment by rnd4222** [comment]
I'm not even sure what definition of arity should be in a language with **1)** polymorphic types and **2)** first-class functions.
Looks like you can't enforce upper argument limit of a function with polymorphic return type, because it can be instantiated to another function type.
I.e., you can say "function of type `'a -> 'b` takes no less than one argument", but you can't say that it's _exactly_ one argument, because `'b` can be instantiated to `'c -> 'd`.

**Comment by Octachron** [comment]
This is definitely not a regression since any use of the ill-defined `run` function leads to a compilation error before 4.08:

```OCaml
type ('r, 'a) t = 'r -> 'a
external run : ('r, 'a) t -> ('r -> 'a) = "%identity"
let error = run succ 0
```
> Fatal error: Cmmgen.transl_prim_2: id

Note that primitives are not OCaml functions by definition, and that there is a well-defined notion of arity for them.

**Comment by gasche** [comment]
For the record, I tested @Octachron examples with a few variations. `('r, 'a) t -> ('r -> 'a)` (as in his example) and `('r -> 'a) -> ('r -> 'a)` both fail, but `('r, 'a) t -> ('r, 'a) t` happens to work.

This does seem to confirm the general idea that `external` primitives are a low-level mechanism with a fragile compilation story (especially in presence of polymorphism), and that it is reasonable to reject cases that are failing the check.

Rejected uses of the `%identity` primitive can be turned into just `fun x -> x`, which is safe and should be optimized correctly in many (but not all) cases. Unfortunately, for people exposing `external .. = "%identity"` in their module signature, this means a signature-breaking change.

**Comment by Octachron** [comment]
Another way to looks at the issue is that toplevel arrows in external declarations are not OCaml arrows, but a different arrow operator with a C-like semantics: for a C function ` int ⟿  (int -> int)` and `int ⟿  int ⟿  int` are very different functions. Similarly, using a type abbreviation works for ` ('a,'b) t -> ('a,'b) arrow` because it precises which arrows are  C-arrows. After a quick check, this point is already mentioned in the manual at the end of https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec416 .
