### ISSUE TITLE
Spurious warning printed by ocamldoc

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7410]
**Original bug ID:** 7410
**Reporter:** kosik
**Assigned to:** @Octachron
**Status:** resolved (set by @gasche on 2016-11-12T16:08:52Z)
**Resolution:** fixed
**Priority:** low
**Severity:** minor
**Version:** 4.02.3
**Fixed in version:** 4.04.0
**Category:** ocamldoc
**Duplicate of:** #7290

## Bug description

If I take a file with the following contents:

  exception E of {foo:unit}

and when I run the following command:

  ocamldoc main.ml

then ocamldoc prints:

  Compilation error(File "odoc_ast.ml", line 1384, characters 37-43: Assertion failed). Use the OCaml compiler to get more details.

despite the fact that the same file is accepted without problems by ocamlc.

**Comment by vicuna** [comment]
**Comment author:** @gasche

ocamldoc in 4.03 did not support inline records. This was fixed by octachron in 4.04.0.

(You indicate that the affected version is 4.02.3, but I think that inline records do not work in 4.02.3, only with 4.03.0 and upwards.)

**Comment by vicuna** [comment]
**Comment author:** kosik

You are right. Thanks!

**Comment by vicuna** [comment]
**Comment author:** @gasche

Please do not hesitate to get in touch if you have any kind of issues on using 4.04 for Coq development.
