### PR TITLE
Do not emit references to dead labels (spacetime)

### PR DESCRIPTION
**Pull request by gretay-js**
Dead code elimination in the backend can remove spacetime instrumentation and labels that spacetime table refers to. The table emitted at the end of a compilation unit still contains references to these now-undefined labels, causing a linker error.  This PR fix it.

For example, the code
```
type op = Eq | Neq
let [@inline always] f a = print_endline (string_of_int a)
let foo op =
  let a = true in
  match op, a with
  | Eq, true -> f 1
  | Neq, true -> f 2
  | _, _ -> f 3
```
fails with a linker error:

``` 
$ ocamlopt test2.ml -o test 
test2.o: In function `camlTest2__spacetime_shapes':
:(.data+0x190): undefined reference to `.L112'
:(.data+0x1a8): undefined reference to `.L111'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
``` 
when compiled with spacetime and without flambda.

With flambda, the `match` is simplified before spacetime table is computed. Without flambda, the calls are instrumented with spacetime and `f` is inlined.  Then, dead code pass in the backend eliminates some of the inlined calls to f, including instrumentation, but spacetime table is not updated.

This is most likely caused by PR #2321 (in 4.10) that eliminates dead handlers, which may include inlined calls, and hence instrumentation and labels. It seems that prior to it, labels have never been eliminated in the backend.

The proposed fix is to keep track of local labels that are emitted for a compilation unit, and then use this information to clean spacetime table right before it is emitted.  The fix is in `amd64/emit.mlp` because spacetime is specific to amd64 and dead code elimination pass is generic. 

Keeping track of emitted labels has some overhead in terms of compilation time and memory, but it is only enabled when the compiler is configured with spacetime. Note that `used_labels` is a superset of labels that spacetime can refer to, but it simplifies the code that keeps track of them.

Testsuite: two tests are currently failing in my setup with spacetime enabled. The failures are unrelated to the PR: they fail without this patch.
- statmemprof/native does not terminate
- output-complete-obj/test fails to find libunwind. 

All other tests pass. The example above compiles and works under spacetime.

### CODE REVIEW

**Comment by gasche** [comment]
Meta-level note: I wonder how important it is to work on fixing spacetime instrumentation in trunk. Last I heard, instrumentation tools where only available for an older version of OCaml, so people would basically use those versions to profile their programs. Are there active users of Spacetime on recent OCaml versions in the wild? If you do not presently have an active need for Spacetime, maybe it's reasonable to invest less resources into fixing it right now.

**Comment by mshinwell** [comment]
@gasche We're using Spacetime to profile Flambda 2.0, so "yes" :)  The existing tools work just fine.

File: asmcomp/amd64/emit.mlp [hunk 1]
```diff
@@ -171,7 +171,18 @@ let emit_label lbl =
 
 let label s = sym (emit_label s)
 
-let def_label s = D.label (emit_label s)
+module Int = Numbers.Int
```
Comment (mshinwell) [inline asmcomp/amd64/emit.mlp]: Let's move this "module" declaration up to the top of file file.

File: asmcomp/amd64/emit.mlp [hunk 2]
```diff
@@ -171,7 +171,18 @@ let emit_label lbl =
...
+
+(* For Spacetime, keep track of code labels that have been emitted.  *)
+let used_labels = ref Int.Set.empty
+
+let mark_used lbl =
+  if Config.spacetime && not (Int.Set.mem lbl !used_labels) then
```
Comment (mshinwell) [inline asmcomp/amd64/emit.mlp]: I'd prefer to see `begin` and `end` around the "`then`" clause.

**Review by mshinwell — CHANGES_REQUESTED** [review]
This is ok for merging after comments addressed.

File: asmcomp/amd64/emit.mlp (hunk 1 above)
Comment (gretay-js) [reply asmcomp/amd64/emit.mlp]: Done. I had to add a new function Numbers.Int.to_string because of a preceding reference to Int.to_string.

File: asmcomp/amd64/emit.mlp (hunk 2 above)
Comment (gretay-js) [reply asmcomp/amd64/emit.mlp]: Fixed.

**Review by mshinwell — APPROVED** [review]

**Comment by gretay-js** [comment]
This should probably be backported to 4.10. The issue it fixes was introduced in PR #2321 which is included in 4.10.

**Comment by gasche** [comment]
(Backporting sounds sensible to me, but I don't have time to do it now. Whoever should feel free to do it, please use `git cherry-pick -x -m 1 <github merge commit>`.)
