### PR TITLE
New GC-pacing logic

### PR DESCRIPTION
**Pull request by damiendoligez**
This is the implementation of https://github.com/damiendoligez/gc-pacing .

Remains to be done:
- [x] update the off-heap and ephemeron allocation counters when promoting blocks
- [x] update the custom-block allocation functions
- [x] debug a few test failures
- [x] rebase onto trunk

This PR is the last item of #14324

cc @tmcgilchrist 

supersedes #10418

### CODE REVIEW

File: runtime/major_gc.c [hunk 1]
```diff
@@ -1097,33 +1160,121 @@ typedef enum {
...
+    /* Start with the oldest phase, finish with the current one. */
+    ph = pp_next (ph);
+    while (1){
+      uintnat adv = pacing_ring[ph].advance_work;
+      w = local_work[ph] + adv;
+      if (w == 0) break;
+      atomic_alloc_counter wc = work_counter;
+      atomic_alloc_counter ac = alloc_counter;
+      diff.on_heap = ac.on_heap - wc.on_heap;
+      diff.off_heap = ac.off_heap = wc.off_heap;
```
Comment (dijkstracula) [inline runtime/major_gc.c]: Pardon the driveby review since I know this is still a draft, but: Should this be `diff.off_heap = ac.off_heap - wc.off_heap;` (`-` rather than `=`) like the lines above and below?  (And, more generally, should this be a macro e.g. `Caml_ac_op(diff, ac, -, wc)`?)

Comment (damiendoligez) [reply runtime/major_gc.c]: Good catch, thanks a lot!

File: runtime/major_gc.c [hunk 2]
```diff
@@ -785,35 +783,145 @@ static void adopt_orphaned_work (int expected_status)
...
+}
+
+static inline pacing_phase pp_phase (void)
+{
+  switch (caml_gc_phase){
+  case Phase_sweep_main: return pp_sweep;
+  case Phase_sweep_and_mark_main: return pp_mark;
+  case Phase_mark_final: return pp_mark;
+  case Phase_sweep_ephe: return pp_ephe;
+  }
```
Comment (edwintorok) [inline runtime/major_gc.c:928]: This fails to build for me with GCC 15.2.1:
```
runtime/major_gc.c: In function ‘pp_phase’:
runtime/major_gc.c:849:1: error: control reaches end of non-void function [[-Werror=return-type](https://gcc.gnu.org/onlinedocs/gcc-15.2.0/gcc/Warning-Options.html#index-Wno-return-type)]
  849 | }
      | ^
```

File: runtime/major_gc.c [hunk 3]
```diff
@@ -769,35 +783,145 @@ static void adopt_orphaned_work (int expected_status)
...
+}
```
Comment (edwintorok) [inline runtime/major_gc.c:930]:
```suggestion
+  CAMLunreachable();
}
```

AFAICT all enum values are handled, so we just need to tell the compiler that.

**Review by edwintorok — COMMENTED** [review]
small fix to make it compile with GCC 15.2.1.

File: runtime/major_gc.c (hunk 2 above)
Comment (damiendoligez) [reply runtime/major_gc.c:928]: thanks

**Comment by udesou** [comment]
@damiendoligez I ran the [macro benchmarks](https://github.com/ocaml-bench/macro-benches/tree/master) we have been setting up with the two runtimes from this PR: [one with the new gc-pacing changes](https://github.com/udesou/ocaml/tree/gc-pacing-new%2Bstdlib-events) and [ocaml trunk](https://github.com/ocaml/ocaml/tree/cfb30145d9e6bbf99c15e875604d5d5fd320589e).

The run is a 5×5 sweep of s ∈ {131072, 262144, 524288, 1048576, 2097152} × o ∈ {40, 80, 120, 150, 200} × 2 runtimes × 22 benches × N=5 invocations per cell (28 benches minus `alt_ergo_*`, `jsoo`, and `pplacer_testsuite` which currently fail to build for trunk-unrelated reasons).

I have uploaded the following artifacts:

- **Logs:** [`results/pr-14796/logs/`](https://github.com/ocaml-bench/macro-benches/tree/master/results/pr-14796/logs): `runbms.yml` (benchmark metadata) + per-(bench, runtime, s, o) `olly_*.json` and `perf_*.json` JSONL sidecars (one line per invocation).
- **Figures** [`results/pr-14796/figs/`](https://github.com/ocaml-bench/macro-benches/tree/master/results/pr-14796/figs) : The heatmaps below.
- **Report:** [`results/pr-14796/report.md`](https://github.com/ocaml-bench/macro-benches/blob/master/results/pr-14796/report.md): Claude-generated report of per-bench breakdown + the trade-off tables.
- **Notebooks:** If you want to explore some initial heatmaps/pareto graphs from the logs, I have committed a copy with all the outputs at [`results/pr-14796/notebooks/`](https://github.com/ocaml-bench/macro-benches/tree/master/results/pr-14796/notebooks).

In general, we observed that the changes seems to improve wall time at the cost of a bit of max RSS. The graphs below seem to confirm the hypothesis that (1) the new pacer improves things across the board, and (2) the default `s` and `o` may not be optimal for the new runtime.

### Cross-runtime: gc-pacing vs trunk, per (s, o)

`liq_video_frames_pool` is excluded from these two aggregates because its non-default-`o` cells thrash the GC and dominate any geometric mean (see the section on it below). The aggregate is over the remaining **22 benchmarks**.

fig7_pr14796_xrt_wall_so_aggregate

fig8_pr14796_xrt_rss_so_aggregate

The new pacer seems faster on **every cell** of the 5×5 sweep but the RSS picture shows the tradeoff between space x time that tends to happen.

### Intra-runtime: gc-pacing with default parameters

fig9_pr14796_intra_gcp_wall_so_aggregate

Here we see the typical space x time GC tradeoff more clearly: moving to larger `s` improves the geomean wall consistently and lowering `s` gets slower across the board. For RSS, lowering `o` is what dominates. 

fig10_pr14796_intra_gcp_rss_so_aggregate

 The interesting Pareto-improving cells seems to be mid-`s`, mid-`o`: `(s=524288, o=80)` is −8.7% RSS and −1.4% wall vs default. That is, the current `(262144, 120)` default may not be on the Pareto frontier for the new pacer as suggested in the issue https://github.com/ocaml/ocaml/issues/14634, e.g.

### `liq_video_frames_pool` thrashes at non-default `o`

`liq_video_frames_pool` is a synthetic benchmark based on [ocaml/ocaml#14533](https://github.com/ocaml/ocaml/issues/14533), it consists of three Bigarrays per iteration sized as 720p YUV420 planes (matching mm's `Image.YUV420.create`) with `LIQ_POOL=1` modelling ffmpeg's `AVFrame`/`av_frame_free` refcounted-pool lifecycle.

On this PR at the default `(262144, 120)` it runs in ~2.2s. At every other cell of the sweep wall time either explodes (15-50× the default) or olly produces negative times because of a timeout. Effectively the bench timeouts or thrashes the GC at non-default `o`.

You can reproduce standalone without any of the benchmark's orchestration plumbing:

```bash
# Bench source: ~/macro-benches/benchmarks/liq-video-frames/liq_video_frames.ml
# Build inside the macro-benches monorepo (duniverse must be populated; see scripts/setup-monorepo.sh):
cd macro-benches
dune build --root . --profile release benchmarks/liq-video-frames/liq_video_frames.exe

EXE=_build/default/benchmarks/liq-video-frames/liq_video_frames.exe

# Default: ~2 seconds wall
LIQ_POOL=1 LIQ_TOUCH=full $EXE 30000

# Lower o: ~37-114 seconds wall (15-50× slowdown)
LIQ_POOL=1 LIQ_TOUCH=full OCAMLRUNPARAM='o=40' $EXE 30000

# Mid o: also pathological (this one was producing dropped-event runs in our setup)
LIQ_POOL=1 LIQ_TOUCH=full OCAMLRUNPARAM='o=80' $EXE 30000
```

The frame count is `Sys.argv.(1)` (default 1). `LIQ_POOL=1` selects the AVFrame refcounted-pool path; `LIQ_TOUCH=full` writes every plane each iteration; the `liq_video_frames.ml` source documents the rest of the knobs in its preamble.

Sorry for the long reply but I hope this helps. Please let me know if you'd like to rerun the benchmarks yourself. I'd be happy to assist with that (until we set up something we can run more automatically on PRs like this one).

**Comment by damiendoligez** [comment]
>liq_video_frames_pool thrashes at non-default o

This is fixed by d99da1984f1f847599ddae0f7719e2bfb7935f4e. It was caused by a rounding problem that forced the GC to do a large number of very small slices.

Thanks for the report and the repro case.

File: runtime/major_gc.c
Comment (edwintorok) [inline runtime/major_gc.c]: Is this cast to `uintnat` still needed here? Both sides are a `double` now.

Comment (damiendoligez) [reply runtime/major_gc.c]: good catch !

**Comment by damiendoligez** [comment]
I've done some measurements to see how well the new pacing logic responds
to the overhead parameter in various conditions.

## First program

The first set of graphs measures the performance of this program:
https://gist.github.com/damiendoligez/6873546560f5b45d4fe171bd48b1a935

In these, the overhead parameter is on the x axis and the
process's RSS is on the y axis. The two solid lines represent the
target: the lower line is the theoretical memory size in the absence of
ephemerons and the upper line is the theoretical maximum memory size in
the presence of ephemerons. Note that "theoretical memory size" is the size
of memory managed by the GC (heap + custom blocks) and does not
include various overheads associated with other parts of the runtime.

These overheads add some unknown offset that corresponds to all the
data structures that are not managed by the GC. I've tried to adapt
some of @stedolan's code to remove the fixed offset but it doesn't
seem to work well here.

The following graph shows what happens when you vary the ratio of
off-heap to on-heap data (on the vertical axis, represented by the "off"
parameter) and the ratio of ephemerons to normal data (horizontal, "ephe"
parameter).

Note that off=4.0 is not really a reasonable value, and I'd be really
surprised to see a use of ephemerons that gets to ephe=0.7. Those are
only included to see what happens in extreme situations.

param-all

Generally, all the points stay close to the target lines, but the
presence of ephemerons seems to impose some kind of off-heap overhead
proportional to o.

Note that the target lines change as `off` varies, because the overhead
is proportional to the heap data, not to the total data. See
https://github.com/damiendoligez/gc-pacing/blob/main/gc-pacing.pdf
for more details.

The next graphs compare this PR with previous versions of OCaml:
4.14.4 and all the 5.x version. One graph with only on-heap data, one with
off-heap data, and one with ephemerons. We can see that the new code
is generally better than what we had before.

compare-1000-0-0
compare-1000-1-0
compare-1000-0-3


## Second program

The next graphs are using @stedolan's program (slightly modified):
https://gist.github.com/damiendoligez/d770be4b69d56925df2cb30195eb03b9

Here, the y axis is the actual overhead as measured by the program.

First, a comparison with some previous versions of OCaml (with `MODE=lists`):

compare-versions

Next, this program has several modes of operations, which change what
kind of allocations it does:
- bigarrays (`ba`)
- byte arrays (`bytes`)
- normal array (`large`)
- lists (`lists`)

I made a graph for each one, and there are some differences. I will
also investigate these differences, and also the difference between
the first program and this program in `large` mode: their allocation
patterns are very similar and I would expect similar performance.

mode-ba
mode-bytes
mode-large
mode-lists

**Comment by gasche** [comment]
Nice! It looks like the new gc-pacing responds very well and is globally closer than previous implementations in tracking what the GC should be doing given the user-provided parameters.

Idle curiosity questions/remarks:

1. The off=4.0 curve in the first multi-picture have a discontinuous bump before overhead=50%; do you know why?
2. Could the gap between the intended line and the real line in the ephe=0.3 and ephe=0.7 cases come from runtime off-heap data structures that track ephemeron blocks? The todo-lists are internal to the ephemeron blocks so they do not create off-heap work, but then we have the ephe-ref-table, which store 4 off-heap words on average per write into an ephemeron block element. (Bigarrays also have this off-heap tracking, which might explain why the green dots in off=4 ephe=0 are also above the intended line.)
3. The only case where you new PR does worse than an existing version is the last graph of the first program, with ephe=0.3, where you do fine but slightly worse than 5.5.0. Understanding why ephemerons seem to cause more off-heap cost than expected would help "fixing" this last case.

**Comment by edwintorok** [comment]
> Note that "theoretical memory size" is the size
of memory managed by the GC (heap + custom blocks) and does not
include various overheads associated with other parts of the runtime.
> These overheads add some unknown offset that corresponds to all the
> data structures that are not managed by the GC. I've tried to adapt
> some of @stedolan's code to remove the fixed offset but it doesn't
> seem to work well here.

Assuming that the runtime tracks its own overhead correctly, then maybe it could self-calibrate on startup for a given size, i.e. something like this to calculate the `offset`:
```
let measure_live_words_delta f =
  Gc.full_major ();
  let q0 = Gc.quick_stat () in
  let r = f () in
  Gc.full_major ();
  let q1 = Gc.quick_stat () in
  let _alive = Sys.opaque_identity r in
  q1.Gc.live_words - q0.Gc.live_words - Obj.reachable_words (Obj.repr q0)

let n = 1000

let make_n () = Array.make n 0

let m = 509
let make_4k () = Array.make_matrix n m 0

let () =
  let delta1 = measure_live_words_delta make_n in
  let offset = delta1 - n in
  Printf.printf "Array %d words -> %d live words, offset = %d\n%!" n delta1 offset;
  let delta2 = measure_live_words_delta make_4k in
  Printf.printf "Array %d*%d words -> %d live words, calculated delta = %d\n%!" n m delta2 (delta2 - (n*(m+offset)+n+offset))
```

Which prints an overhead of 1 word for small arrays (`n=100`), and 3 words for large (`n=1000`). I was a bit surprised to see a non-constant overhead here,, but `LARGE_ALLOC_HEADER_SZ` explains it.
I confirmed with gdb that the inner allocations actually call `malloc(4096)`. Of course the C allocator will have its own overhead, which is not tracked here.
Bigarrays also allocate some values on the OCaml heap, so that should probably be taken into consideration when calculating bigarray to ocaml ratios, it could probably self-calibrate in a similar way (again, assuming that the GC statistics correctly account for the overhead).

Edit: I sent some suggestions on how to tweak and measure the constants to https://gist.github.com/damiendoligez/6873546560f5b45d4fe171bd48b1a935?permalink_comment_id=6242979#gistcomment-6242979,
e.g. on OCaml 5.5 `s_ovh` should be 18 instead of 16.

**Comment by edwintorok** [comment]
RSS vs on/off heap allocations can still have unknown offsets though. Even after a `Gc.compact()`, if you look at `Gc.free_words` it will be non-zero, and some of the small allocations might reuse that instead of having to increase heap size.  (or perhaps Gc.free_words at measurement start could be used as a correction offset, if we sample an up-to-date value).

Although measuring RSS is very useful as an end-user measure, for the purposes of measuring GC space overhead correctness it might be better to also measure quantities that the GC can see and control directly.
Now that the GC keeps track of off-heap data in bytes (instead of as a ratio to heap size), maybe we should extend the `Gc.stat` type to also report how many off-heap bytes we have allocated, and how many we have live.
Then we could measure space overhead at runtime without having to look at RSS at all.
(being able to query the used custom memory from within OCaml would also be more generally useful, and I was actually waiting for this PR to be merged before proposing it, but it might be useful for this PR itself)

P.S.:  I should've said this earlier: the results from the graphs are very impressive, thanks a lot for working on this!

**Comment by damiendoligez** [comment]
@gasche 

> 1. The off=4.0 curve in the first multi-picture have a discontinuous bump before overhead=50%; do you know why?

I don't know. In that part of the curve, the heap size stays exactly constant, and the RSS is constant modulo some noise.
I'll try to investigate.

> 2. Could the gap between the intended line and the real line in the ephe=0.3 and ephe=0.7 cases come from runtime off-heap data structures that track ephemeron blocks? The todo-lists are internal to the ephemeron blocks so they do not create off-heap work, but then we have the ephe-ref-table, which store 4 off-heap words on average per write into an ephemeron block element. (Bigarrays also have this off-heap tracking, which might explain why the green dots in off=4 ephe=0 are also above the intended line.)

For bigarrays, this overhead is very dependent on the size of the bigarrays (the `s_off` variable in the program) : when it goes from 2048 to 2049 (with o=100) the max RSS jumps from 122M to 154M for a target of 119. I'm going to blame `malloc` overhead for this one. BTW I'm running all these on MacOS. I'll try Linux later to see if `malloc` behaves better.

For ephemerons, I don't know. I'm not modifying any ephemeron fields, so I'd expect the `ephe-ref-table` to stay empty.

> 3. The only case where you new PR does worse than an existing version is the last graph of the first program, with ephe=0.3, where you do fine but slightly worse than 5.5.0. Understanding why ephemerons seem to cause more off-heap cost than expected would help "fixing" this last case.

Indeed, but I'd say this is low-priority compared to running benchmarks on real programs.

**Comment by damiendoligez** [comment]
@edwintorok 

> Which prints an overhead of 1 word for small arrays (`n=100`), and 3 words for large (`n=1000`). I was a bit surprised to see a non-constant overhead here,, but `LARGE_ALLOC_HEADER_SZ` explains it.

I didn't expect that. The GC is counting 1 word of header for every block. I think it would be rather hard to make it variable without slowing down everything. Besides...

> I confirmed with gdb that the inner allocations actually call `malloc(4096)`. Of course the C allocator will have its own overhead, which is not tracked here.

Yes, the C allocator overhead is the big variable here, and there's nothing much we can do about it.

> Bigarrays also allocate some values on the OCaml heap, so that should probably be taken into consideration when calculating bigarray to ocaml ratios

Yes, I did that.

>RSS vs on/off heap allocations can still have unknown offsets though. Even after a Gc.compact(), if you look at Gc.free_words it will be non-zero, and some of the small allocations might reuse that instead of having to increase heap size. (or perhaps Gc.free_words at measurement start could be used as a correction offset, if we sample an up-to-date value).

It's not so easy because the `Gc.free_words` is part of the overhead that the GC is trying to maintain according to `o`...
Even after a `Gc.compact` it would be best to keep some amount of free list for the next allocations (although I don't remember whether we are doing it now).

>Although measuring RSS is very useful as an end-user measure, for the purposes of measuring GC space overhead correctness it might be better to also measure quantities that the GC can see and control directly.

I did that: in the first set of graphs, the purple points are the heap size as known to the GC. On the first line they stays quite close to the target line. When off-heap memory comes into play, we can't use it directly.

>Now that the GC keeps track of off-heap data in bytes (instead of as a ratio to heap size), maybe we should extend the Gc.stat type to also report how many off-heap bytes we have allocated, and how many we have live.
Then we could measure space overhead at runtime without having to look at RSS at all.
(being able to query the used custom memory from within OCaml would also be more generally useful, and I was actually waiting for this PR to be merged before proposing it, but it might be useful for this PR itself)

But the GC doesn't know how much off-heap memory is alive. That's why the *total* overhead is proportional to the live *on-heap* memory. Keeping track of live off-heap memory would entail a very annoying API change (adding a call to a GC bookkeeping function at every deallocation of off-heap memory).

>P.S.: I should've said this earlier: the results from the graphs are very impressive, thanks a lot for working on this!

Thanks for the encouragement.

**Comment by edwintorok** [comment]
> @edwintorok
> 
> > Which prints an overhead of 1 word for small arrays (`n=100`), and 3 words for large (`n=1000`). I was a bit surprised to see a non-constant overhead here,, but `LARGE_ALLOC_HEADER_SZ` explains it.
> 
> I didn't expect that. The GC is counting 1 word of header for every block. I think it would be rather hard to make it variable without slowing down everything. Besides...

`large_words` and `swept_words` already seems to account for the extra header for large arrays, not sure whether anything else would be needed.
Although  I don't see equivalent accounting for the small sizeclass pools  (other than `frag_words` which isn't used by pacing AFAICT).
I'm not sure what would be the best way to account for it, it could be added to the allocation size for pacing purposes, and `pool_sweep` already has a `wh` variable that holds the entire slot size, so it could use that for `swept_words`.
Maybe additional array reads can be avoided, and it wouldn't necessarily slow things down to account for the fragments.

I attempted to write a program to explore what effect this has on the GC ([overhead.ml](https://gist.github.com/edwintorok/eaff30c2cddf23c5cdc85b1a1e465e36)).

<details>
<summary> RSS increased (~1.5x original),  execution time decreased (by about ~0.95x original). </summary>

5.5:
```
top_heap: 110341 KiB
space_overhead ((top_heap_words - exact_live)/exact live): 169%
space_overhead (configured): 120%
5.23user 0.10system 0:05.34elapsed 99%CPU (0avgtext+0avgdata 123980maxresident)k
0inputs+0outputs (0major+75530minor)pagefaults 0swaps
```

Base of this PR (commit e53a032298229338268c3dc3640214e1fa710c95):
```
top_heap: 111502 KiB
space_overhead ((top_heap_words - exact_live)/exact live): 173%
space_overhead (configured): 120%
5.32user 0.08system 0:05.41elapsed 99%CPU (0avgtext+0avgdata 121300maxresident)k
0inputs+0outputs (0major+54933minor)pagefaults 0swaps
```

this PR:
```
top_heap: 159891 KiB
space_overhead ((top_heap_words - exact_live)/exact live): 291%
space_overhead (configured): 120%
5.08user 0.07system 0:05.16elapsed 99%CPU (0avgtext+0avgdata 182064maxresident)k
0inputs+0outputs (0major+48906minor)pagefaults 0swaps
```
</details>

Although in the end this is a corner case, so I'd ignore it for the purposes of this PR, unless you think there is something else wrong here that is worth investigating.

> > I confirmed with gdb that the inner allocations actually call `malloc(4096)`. Of course the C allocator will have its own overhead, which is not tracked here.
> 
> Yes, the C allocator overhead is the big variable here, and there's nothing much we can do about it.

Agreed (there is `malloc_usable_size` on Linux, but it isn't portable)

**Comment by udesou** [comment]
Hi @damiendoligez, 

I reran the macrobenchmarks with the latest changes you have ([72c712d](https://github.com/udesou/ocaml/commit/72c712d414aa46e2e524bb2f7d1cd43abc76cb37) vs [e53a0322](https://github.com/ocaml/ocaml/commit/e53a032298229338268c3dc3640214e1fa710c95)). 

To make the results easier to explore, I also put together a small dashboard that generates interactive graphs from the benchmark logs. If you have Docker installed, you can run it with:

```
docker run --rm -p 8080:80 ghcr.io/udesou/ocaml-bench-dashboard:pr14796-s-o-native
```

and then open `http://localhost:8080/`. 

For these runs, I performed a parameter sweep over:

* s: [131072, 262144, 524288, 1048576, 2097152]
* o: [40, 80, 120, 150, 200]

Overall, it seems that the new gc-pacer mostly improved all benchmarks, with a few small regressions that could be just noise. Note that the different parameters may influence those results, which you can see through the heatmaps.

I have also created a separate run with benchmarks that exercise off heap allocation with a sweep over:

*  M: [11, 22, 44, 100, 250]
*  o: [40, 80, 120, 150, 200]

```
docker run --rm -p 8080:80 ghcr.io/udesou/ocaml-bench-dashboard:pr14796-M-o-offheap
```

To know more about each benchmark, I got Claude to write a quick summary in https://github.com/ocaml-bench/macro-benches/tree/master/docs/benchmarks.

I’d really appreciate any feedback on both the benchmark visualizations and the dashboard itself, either here or by email. It would help us improve the tooling and make future benchmarking results more useful.
